name = "jz-chat-worker"
main = "src/worker.js"
compatibility_date = "2025-01-15"

[durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiter" }
]

[[migrations]]
tag = "v1-rate-limiter"
new_sqlite_classes = ["RateLimiter"]

[vars]
# Comma-separated list of allowed Origins for CORS.
# Localhost is intentionally excluded; the Worker rejects localhost requests.
ALLOWED_ORIGINS = "https://jerryz123.github.io,https://jzhao.me,https://www.jzhao.me"
# Retrieval store id (optional). If unset, retrieval is disabled and Chat Completions is used.
VECTOR_STORE_ID = "vs_68ab7e653204819180b0b363149f4b02"
# Default model used by the Worker (can be overridden per request)
MODEL = "gpt-4.1-mini"
