name = "jz-chat-worker"
main = "src/worker.js"
compatibility_date = "2025-01-15"

[vars]
# Default model; replace with your fine‑tuned model id, e.g.:
# MODEL = "ft:gpt-4o-mini:your-org:your-suffix:2024-08-12"
MODEL = "gpt-4o-mini"
# Comma-separated list of allowed Origins for CORS
ALLOWED_ORIGINS = "https://jerryz123.github.io,http://localhost:8000"
# Optional: override the OpenAI API base (e.g., a gateway)
OPENAI_API_BASE = "https://api.openai.com"

