name = "jz-chat-worker"
main = "src/worker.js"
compatibility_date = "2025-01-15"

[durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiter" }
]

[[migrations]]
tag = "v1-rate-limiter"
new_sqlite_classes = ["RateLimiter"]

[vars]
# Comma-separated list of allowed Origins for CORS (dev includes localhost)
ALLOWED_ORIGINS = "https://jerryz123.github.io,https://jzhao.me,https://www.jzhao.me,http://localhost:8000"
# Retrieval store id (optional). If unset, retrieval is disabled and Chat Completions is used.
VECTOR_STORE_ID = "vs_68ab7e653204819180b0b363149f4b02"
# Default model used by the Worker (can be overridden per request)
MODEL = "gpt-5-mini-2025-08-07"

# Production environment overrides (no localhost in CORS)
[env.production]
[env.production.vars]
ALLOWED_ORIGINS = "https://jerryz123.github.io,https://jzhao.me,https://www.jzhao.me"
VECTOR_STORE_ID = "vs_68ab7e653204819180b0b363149f4b02"
MODEL = "gpt-5-mini-2025-08-07"

[env.production.durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiter" }
]
